pg:
  image: postgres:13
  restart: "always"
  environment:
    POSTGRES_DB: pg
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: secret
  ports:
    - "5432:5432"
  volumes:
    - ./db:/var/lib/postgresql/data
